# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/amir/Documents/CS Masters/Robotics/Final Project"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/amir/Documents/CS Masters/Robotics/Final Project"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/amir/Documents/CS Masters/Robotics/Final Project/CMakeFiles" "/home/amir/Documents/CS Masters/Robotics/Final Project/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/amir/Documents/CS Masters/Robotics/Final Project/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named min

# Build rule for target.
min: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 min
.PHONY : min

# fast build rule for target.
min/fast:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/build
.PHONY : min/fast

MyQueryHandler.o: MyQueryHandler.cpp.o

.PHONY : MyQueryHandler.o

# target to build an object file
MyQueryHandler.cpp.o:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/MyQueryHandler.cpp.o
.PHONY : MyQueryHandler.cpp.o

MyQueryHandler.i: MyQueryHandler.cpp.i

.PHONY : MyQueryHandler.i

# target to preprocess a source file
MyQueryHandler.cpp.i:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/MyQueryHandler.cpp.i
.PHONY : MyQueryHandler.cpp.i

MyQueryHandler.s: MyQueryHandler.cpp.s

.PHONY : MyQueryHandler.s

# target to generate assembly for a file
MyQueryHandler.cpp.s:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/MyQueryHandler.cpp.s
.PHONY : MyQueryHandler.cpp.s

dialog.o: dialog.cpp.o

.PHONY : dialog.o

# target to build an object file
dialog.cpp.o:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/dialog.cpp.o
.PHONY : dialog.cpp.o

dialog.i: dialog.cpp.i

.PHONY : dialog.i

# target to preprocess a source file
dialog.cpp.i:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/dialog.cpp.i
.PHONY : dialog.cpp.i

dialog.s: dialog.cpp.s

.PHONY : dialog.s

# target to generate assembly for a file
dialog.cpp.s:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/dialog.cpp.s
.PHONY : dialog.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/main.cpp.s
.PHONY : main.cpp.s

mainwindow.o: mainwindow.cpp.o

.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i

.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s

.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

moc_dialog.o: moc_dialog.cpp.o

.PHONY : moc_dialog.o

# target to build an object file
moc_dialog.cpp.o:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/moc_dialog.cpp.o
.PHONY : moc_dialog.cpp.o

moc_dialog.i: moc_dialog.cpp.i

.PHONY : moc_dialog.i

# target to preprocess a source file
moc_dialog.cpp.i:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/moc_dialog.cpp.i
.PHONY : moc_dialog.cpp.i

moc_dialog.s: moc_dialog.cpp.s

.PHONY : moc_dialog.s

# target to generate assembly for a file
moc_dialog.cpp.s:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/moc_dialog.cpp.s
.PHONY : moc_dialog.cpp.s

moc_mainwindow.o: moc_mainwindow.cpp.o

.PHONY : moc_mainwindow.o

# target to build an object file
moc_mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/moc_mainwindow.cpp.o
.PHONY : moc_mainwindow.cpp.o

moc_mainwindow.i: moc_mainwindow.cpp.i

.PHONY : moc_mainwindow.i

# target to preprocess a source file
moc_mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/moc_mainwindow.cpp.i
.PHONY : moc_mainwindow.cpp.i

moc_mainwindow.s: moc_mainwindow.cpp.s

.PHONY : moc_mainwindow.s

# target to generate assembly for a file
moc_mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/min.dir/build.make CMakeFiles/min.dir/moc_mainwindow.cpp.s
.PHONY : moc_mainwindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... min"
	@echo "... MyQueryHandler.o"
	@echo "... MyQueryHandler.i"
	@echo "... MyQueryHandler.s"
	@echo "... dialog.o"
	@echo "... dialog.i"
	@echo "... dialog.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... moc_dialog.o"
	@echo "... moc_dialog.i"
	@echo "... moc_dialog.s"
	@echo "... moc_mainwindow.o"
	@echo "... moc_mainwindow.i"
	@echo "... moc_mainwindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

